refactor: frontend global types
jwsmith24/palette pull request #52
Opened 2024-10-31 23:55 UTC by jwsmith24

- Extend global types for the frontend scope to require the key field and add any utility functions
- Refactor all frontend modules to utilize the new types
- Add additional comments
- Minor configuration updates to get the linter to stop yelling

Tested running in Docker and locally

2024-11-01 18:10 UTC, cmccand1 requested changes

2024-11-01 23:13 UTC, jwsmith24 commented on .gitignore
cause I'm silly

2024-11-01 23:14 UTC, jwsmith24 commented
Keeping this as a draft for now until the new global types drop

2024-11-02 13:47 UTC, jwsmith24 commented
@cmccand1 I added the useFetch hook before I head out for the day!

It's not implemented by anything yet, but it essentially integrates the fetchAPI you wrote directly into a react hook to easily update state, error messages, loading indicators, etc and can be reused in any component to handle fetch requests!

I also updated the organization of the frontend structure and updated some of the names to be a bit more clear. 

Keeping this as a draft, but just wanted to you to be able to see where I'm at for reference.

2024-11-02 22:10 UTC, closed without merging