refactor: update controller
jwsmith24/palette pull request #98
Opened 2024-11-13 01:07 UTC by jwsmith24

Everything from #97 plus:

- refactored update logic and consolidated to `rubricController`
- remove template-related controller files to reduce clutter

2024-11-13 03:54 UTC, cmccand1 commented on palette-types/src/canvasProtocol/canvasRubricRequests.ts
> +  rubric_id: number;
Canvas has this field as id and not rubric_id

see: https://canvas.instructure.com/doc/api/rubrics.html#method.rubrics.update

2024-11-13 03:55 UTC, cmccand1 commented on backend/src/__tests__/canvasAPITests/rubricsAPI/updateRubricTests.test.ts
> +      rubric_id: 123,
Canvas has this field as id and not rubric_id

See: https://canvas.instructure.com/doc/api/rubrics.html#method.rubrics.update

2024-11-13 04:02 UTC, cmccand1 commented on backend/src/canvasAPI/rubricRequests.ts
I realize I made this confusing by making some request types match the request body expected by Canvas while others are just a wrapper for the params to put in the api request url...

I'm ok with doing what you did here as long as it doesn't affect Canvas' handling of the request, i.e. it still works with the extra field. Did you test this with a real api call?

2024-11-13 04:04 UTC, cmccand1 commented on palette-types/src/index.ts
Me likey

2024-11-13 04:05 UTC, cmccand1 requested changes
See individual comments

2024-11-13 12:09 UTC, jwsmith24 commented on backend/src/canvasAPI/rubricRequests.ts
I definitely thought these were just wrappers! So that makes sense lol

We don't specifically have a way to trigger a real update yet in the app since canvas automatically makes copies. I have to take another look and see if Canvas sends any flag if it did make a copy.

2024-11-13 12:20 UTC, jwsmith24 commented on backend/src/canvasAPI/rubricRequests.ts
Wish I didn't have to go into work mid thought haha but yeah I'll need to rework after understanding those request types better! Stay tuned

2024-11-13 22:11 UTC, jwsmith24 commented
latest push adds the first round of frontend refactoring to better align with the Canvas API while maintaining a nice UX

2024-11-13 22:11 UTC, jwsmith24 commented
still WIP to address previous issues

2024-11-14 18:44 UTC, jwsmith24 commented
Reorganized duplicate rubric handling on the frontend to align with new design pattern.

Next phase will be updating the protocol modules to ensure the course and assignment associations are applied properly.

2024-11-14 18:46 UTC, jwsmith24 commented
Also added a simple loading component to display during fetches!

2024-11-15 22:56 UTC, closed without merging